* 9-9
  name five big-world wide orgnization have large influence? 
  world bank
  united union?
  google
** Introduction
   page 9 T / Fa
   page 16
   Exhibit 1.3

** definitions 
*** Define organization and their basic characteristics:
    organizations: ***social inventions*** for accomplishing common goals ***(goal accomplishemnt)*** through ***group effort***
*** the field of organizational behaviour is about understanding people and managing them to work effectively
*** the field of organizational behaviour is concerned with how organizations can survive and adapt to change
*** Explain the concept of organizational behaviour and desbribe the goals of the field
    organizational behaviour: the attitudes and behaviours of individuals and groups in organizations
*** Human resources management 
    programs practices and systems to acquire develop motivate and retain employees in organizations
*** Define management and describe what managers do to accomplish goals
    management: the art of getting things accomplished in organizations through others
*** evidence-based management: Translating principles based on the best scientific evidence into organizational practices
*** Contrast the classical viewpoint of management with that advocated by the human relations movement
    classical viewpoint: an early prescription on management that advocated a high specialization of labour intensive coordination, and centralized decision making

    Scientic management: Frederick Taylor's system for using research to determine the optimum degree of specialization and standardization of work tasks

    Bureaucracy: Max Weber's ideal type of organization that included a strict chain of command, detailed rules, high specialization, centralized power, and selection and promotion based on technical competence

    Hawthorne studies: Research conducted in the 1920s and 1930s at the Hawthorne plant of Western Electric near Chicago that illustrated how psychological and social processes affect productivity and work adjustment

    Human relations movement: A critique of classical management and bureaucracy that advoated management styles that were more partivipative and oriented toward employee needs.
*** Contingency approch: An approach to management that reconfizes that there is no one best way to manage, and that an appropriate management style depends on the demands of the situation. 
*** Mintzberg's managerial roles
    Informational Roles
    Monitor
    Disseminator
    Spokesperson

    Interpersonal Roles
    Figurehead
    Leader
    Liaison

    Decisional Roles
    Entrepreneur
    Disturbance handler
    Resource allocator
    Negotiator

*** Managerial Roles
   Interpersonal roles
   Informational roles
   Decisional roles
   
*** Managerial Agendas
   Agenda setting
   Networking
   Agenda Implementation

*** workplace spirituality
    A workplace that provides employees with 
