* 9-7
** ways we support the community
   mentorship & programs
   talent & student membership
   community meetups & events
   workspace
** tech-enabled product
   1.it is scalable
   2.the possibility to expand
*** stephanie enders --marketing and growth strategist --sales manager
** strtegy 
   start with previous 5 years plan
***   operating plan
***   financial model
   no business plan survive first contact with customners
   planning before the plan
***   bus canvas
    1.orgaize our thinking
    2.get out the building
    use the model to cathch the model hypothsis
** page 60 of running lean by ash maurya
** getting a business idea to business model
   meet the customers
   fincinal stainable
   organize
** sketching the lean canvas
   balnk section are ok
   think in present terms
   use a customer centric approach

** lean canvas model worksheet
** problem/hypothesis statement
    the colser you can get to the tiniest customer problem the easier it will be to test
****    I believe <people> experience <problem> when doing <task>
****    I believe <people> experience <problem> because of <constraint>
     think some small problems
     *problem: farmers experience sadness when family leaves products no cash = small manufactors rage when the pos systems dont match = yuppies experience when avoiding farmers market due to a lack of cash
** Customer Segments
   who do you aim to reach? Access? Serve? Ignore?
   ****customer: what are the thing that will make more detailed cusomters
   top priority
   easy to access
   ignoring(for now)
** Unique Value Propsosition
   Unique Value Proposition
   Feelings = Value
   Reason = Solution
   Tin man vs. Scarecrow
*** capture the emotion on the advertisement
    know customer better and change the emotion
    Explore the unique feelings you want to evoke in your customer!
    1. Find the emotion
    2. Identity the outcome
    3.Link to an elememt of your solution
    *****unique value confidence containable cash more fix cost
   
    solutions:
    DOs:literate  Pivot  List Capabilities
    Donts: Create Full Solution ,List all Feature ,Fall in love
** introduce ur problem first  
   introduce the problem ur solving first not the man himself
** Channel# SALES
   (How your product reaches your customers)
   Product
   Physical | Virtual
   Channel
   Physical | Virtual
** Channel* Marketing
   How to reach ur customers
   Email Marketing,Offline Events,SEO...
   What are some other marketing and sales channels
** Revenue
   asset sale :Mug
   Usage fee : Business Model 101
   Subscritpion: Preflight
   Advertising: PwC partnership
   Lending/resale:Coworking
   Licensing:Curriculum
   Brokerage Fee:N/A
** Pirate Metrics,AARRR-Dave McClure
   hwo to users find you
   do users have a great first experience?
   Do users come back?
   How do you make money?
   Do users tell others?
** what now
   pick one box that you want to focus on , and create a goal for yourself.
   1.set goal for yourself,what do you think youc anrealistically do in the next week
   2. book a meeting with us to talk about your progress and about future steps
     
   
